[package]
name = "xdp-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
aya = { version = "0.13.1", features = ["tokio"] }
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.45", features = ["full"] }
